spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employers
    username: postgres
    password: 123456
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
#  spring.datasource.driver-class-name=org.postgresql.Driver
#
##spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/books
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.datasource.initialization-mode=always
